[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "leukemia_detection"
version = "0.1.0"
description = "Leukemia detection pipeline"
authors = [{ name = "Your Name" }]
requires-python = ">=3.8"
dependencies = []