# Binary Classification Configuration

# Classification mode
classification_mode: "binary"

# Paths
output_dir: "../results/cell_inference/resnet18/bbox0.63"
img_dir: "../results/patch_extraction/bbox0.63"
model_path: "../results/cell_classification_onlytrain/resnet18/binary/best_binary_classification_model.pth"
model_name: "resnet18"

# Inference parameters
confidence_threshold_high: 0.9
confidence_threshold_low: 0.1
uncertainty_threshold: 0.1
