# Model
train_neck_only: true
freeze_image_encoder: true
freeze_mask_decoder: true
freeze_prompt_encoder: true

# Loss
focal_loss_weight: 100.0
dice_loss_weight: 1.0
boundary_loss_weight: 1.0
focal_alpha: 0.25
focal_gamma: 2.0
dice_smooth: 1.0
use_boundary_loss: false

# Checkpointing
keep_best_only: false
keep_last_n: 3

# Data
num_workers: 4
pin_memory: true
preeval: false

# Training basics
training_strategy: train_val_split
epochs_s2: 500
batch_size: 2
use_scheduler: false
scheduler: plateau
optimizer: adamw
learning_rate: 0.00001
weight_decay: 0.0001
ohem_fraction: 0.1
ohem_hard_weight: 2.0
ohem_hard_weight_max: 2.5
ohem_hard_weight_min: 1.2
online_hard_negative_mining: true
online_hard_negative_mining_weighted: true
grad_clip: 1.0

# Early stopping
patience: 15
min_delta: 0.000001

# Logging and output
output_dir: ../output
output_name: cellsam_experiment
debug: true
log_freq: 10
save_freq: 25
visualization_frequency: 2
visualize_masks: true
save_checkpoints: true
save_visualizations: true
max_visualizations_per_epoch: 4

# Reproducibility
random_seed: 42